### ISSUE TITLE
Unable to load the pretrained model

### ISSUE THREAD

**Issue by sachincse** [tobiassteidle/ML_IDCard_Segmentation_Pytorch#2]
Load model...  ./pretrained/model_final.pt
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    main()
  File "test.py", line 50, in main
    checkpoint = torch.load(pathlib.Path(MODEL_FILE))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by tobiassteidle** [comment]
Hi,
please try this download: https://drive.google.com/file/d/1u88se4-G0F-r_ntqm3IblhzMkgxMbzVN/view?usp=sharing

**Comment by sachincse** [comment]
Thank you so much...
