### ISSUE TITLE
NotADirectory ERROR (prepare_dataset.py)

### ISSUE THREAD

**Issue by hdm30** [tobiassteidle/ML_IDCard_Segmentation_Pytorch#5]
Hello,

I had the following issue when i run prepare_dataset.py, it seems that's coming from the wget.
Many thanks in advance.

 Dataset available...  dataset/data/01_alb_id
Downloading: ftp://smartengines.com/midv-500/dataset/01_alb_id.zip
100% [......................................................................] 656880207 / 656880207Traceback (most recent call last):
  File "/home/XXXX/anaconda3/envs/idcard3-9/lib/python3.9/shutil.py", line 825, in move
    os.rename(src, real_dst)
NotADirectoryError: [Errno 20] Not a directory: '/home/XXXX/ID_card_detector/ML_IDCard_Segmentation_Pytorch/01_alb_id.zip.uruzlazt.tmp' -> 'dataset/data/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXX/anaconda3/envs/idcard3-9/lib/python3.9/shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
IsADirectoryError: [Errno 21] Is a directory: 'dataset/data/'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/XXXX/ID_card_detector/ML_IDCard_Segmentation_Pytorch/prepare_dataset.py", line 225, in <module>
    main()
  File "/home/XXXX/ID_card_detector/ML_IDCard_Segmentation_Pytorch/prepare_dataset.py", line 219, in main
    download_and_unzip()
  File "/home/XXXX/ID_card_detector/ML_IDCard_Segmentation_Pytorch/prepare_dataset.py", line 122, in download_and_unzip
    wget.download(link, TARGET_PATH)
  File "/home/XXXX/anaconda3/envs/idcard3-9/lib/python3.9/site-packages/wget.py", line 320, in download
    shutil.move(tmpfile, filename)
  File "/home/XXXX/anaconda3/envs/idcard3-9/lib/python3.9/shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "/home/XXXX/anaconda3/envs/idcard3-9/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/XXXX/anaconda3/envs/idcard3-9/lib/python3.9/shutil.py", line 292, in copyfile
    raise FileNotFoundError(f'Directory does not exist: {dst}') from e
FileNotFoundError: Directory does not exist: dataset/data/

**Comment by tobiassteidle** [comment]
Hi @hdm30,
please try to create the "data" subdirectory in directory "dataset/".
The folder structure should be "./dataset/data".
This should work.
